title: myddleton-grange
description: The Myddleton Grange Community Website
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

github:
  is_project_page: false

gems:
- jekyll-mentions
